on:
  push:

env:
  NODE_VERSION: 24
  BUN_VERSION: 1.3.2

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Get cache key
        id: cache-key
        run: |
          bun_lock_hash=$(bun pm hash)
          echo "CACHE_KEY=${{ runner.os}}-$bun_lock_hash" >> "$GITHUB_OUTPUT"
      - uses: actions/cache/restore@v4
        id: check-cache
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          lookup-only: true
          path: &cachePaths |
            ~/.bun/install/cache
            ~/.cache/ms-playwright

      - name: Install dependencies
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          bun install
          bun x playwright install

      - uses: actions/cache/save@v4
        if: steps.check-cache.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: *cachePaths

  check-formatting:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/cache/restore@v4
        with: &cacheRestore
          key: ${{ needs.install.outputs.cache-key }}
          path: *cachePaths
      - run: bun install
      - run: bun run format:check

  unit-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/cache/restore@v4
        with: *cacheRestore
      - run: bun install
      - run: bun run test:unit

  browser-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/cache/restore@v4
        with: *cacheRestore
      - run: bun install
      - run: bun run test:browser
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-traces
          path: ./vitest-traces
          if-no-files-found: ignore

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/cache/restore@v4
        with: *cacheRestore
      - run: bun install
      - run: bun run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
